name: 🔧 Compatibility Issue
description: Report compatibility problems with VS Code, Node.js, or other software 🔗
title: '[Compatibility]: '
labels: ['compatibility', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # 🔧 Compatibility Issue Report

        Thanks for reporting a compatibility issue! We strive to make **Keypress Notifications** work seamlessly across all supported environments. 🌍

        **Before submitting:** Please check our [compatibility matrix](https://vijay431.github.io/vscode-keypress_snackbar_notification-extension/#compatibility) to see if your configuration is officially supported.

  - type: dropdown
    id: compatibility-type
    attributes:
      label: 🔗 Compatibility Issue Type
      description: What type of compatibility issue are you experiencing?
      options:
        - 💻 VS Code version compatibility
        - 🟢 Node.js version compatibility
        - 🖥️ Operating system compatibility
        - 🔌 Extension conflict/interaction
        - ⌨️ Keyboard layout compatibility
        - 🌍 Locale/language compatibility
        - 🎨 Theme compatibility
        - 🏗️ Architecture compatibility (x64, ARM, etc.)
        - 🐳 Development environment (Docker, WSL, etc.)
        - 🔄 Migration/upgrade issues
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: compatibility-description
    attributes:
      label: 🔍 Compatibility Issue Description
      description: Describe the compatibility problem you're experiencing.
      placeholder: |
        Example: Extension fails to activate on VS Code Insiders 1.96.0 with Node.js 22.1.0. Error message indicates incompatible API usage.
    validations:
      required: true

  - type: dropdown
    id: vscode-version
    attributes:
      label: 💻 VS Code Version & Channel
      description: What version and channel of VS Code are you using?
      options:
        - VS Code Stable (latest)
        - VS Code Stable (1.95.x)
        - VS Code Stable (1.94.x)
        - VS Code Stable (1.93.x)
        - VS Code Stable (1.92.x)
        - VS Code Stable (1.91.x)
        - VS Code Stable (1.90.x)
        - VS Code Stable (older)
        - VS Code Insiders (latest)
        - VS Code Insiders (specific build)
        - VS Code Exploration Builds
        - Custom VS Code build
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: vscode-exact-version
    attributes:
      label: 🔢 Exact VS Code Version
      description: What's the exact VS Code version? (Help > About)
      placeholder: 'e.g., 1.95.2 (commit 4710f68) or 1.96.0-insider (commit abc123)'
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: 🖥️ Operating System
      description: What operating system and version?
      options:
        - Windows 11 (latest)
        - Windows 11 (specific version)
        - Windows 10 (latest)
        - Windows 10 (older version)
        - macOS Sonoma (14.x)
        - macOS Ventura (13.x)
        - macOS Monterey (12.x)
        - macOS Big Sur (11.x)
        - macOS (older)
        - Ubuntu 22.04 LTS
        - Ubuntu 20.04 LTS
        - Ubuntu (other version)
        - Debian (latest)
        - Debian (other version)
        - Fedora (latest)
        - CentOS/RHEL
        - Arch Linux
        - Other Linux distribution
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: os-exact-version
    attributes:
      label: 🔢 Exact OS Version & Architecture
      description: Provide exact OS version and architecture (x64, ARM64, etc.)
      placeholder: 'e.g., Windows 11 22H2 (Build 22621.2715) x64, macOS 14.2.1 ARM64, Ubuntu 22.04.3 LTS x86_64'
    validations:
      required: true

  - type: dropdown
    id: node-version
    attributes:
      label: 🟢 Node.js Version
      description: What Node.js version? (Check with `node --version`)
      options:
        - Node.js 22.x (latest)
        - Node.js 22.x (specific version)
        - Node.js 20.x LTS (latest)
        - Node.js 20.x LTS (specific version)
        - Node.js 18.x LTS
        - Node.js 16.x (EOL)
        - Node.js 14.x (EOL)
        - Node.js (other/older)
        - Not sure / Don't know
        - Not applicable
    validations:
      required: true

  - type: input
    id: node-exact-version
    attributes:
      label: 🔢 Exact Node.js Version
      description: What's the exact Node.js version if known?
      placeholder: 'e.g., v20.10.0, v22.1.0'
    validations:
      required: false

  - type: input
    id: extension-version
    attributes:
      label: 📦 Extension Version
      description: What version of Keypress Notifications?
      placeholder: 'e.g., 0.1.0'
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: How can we reproduce this compatibility issue?
      placeholder: |
        1. Install VS Code Insiders 1.96.0-insider
        2. Install Node.js 22.1.0
        3. Install Keypress Notifications extension
        4. Attempt to activate extension
        5. Observe activation failure
      value: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What should happen in a compatible environment?
      placeholder: |
        Example: Extension should activate normally and provide notification functionality regardless of Node.js version within supported range.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happens that indicates incompatibility?
      placeholder: |
        Example: Extension fails to activate with error "Cannot resolve module" in the output console. VS Code shows extension as installed but inactive.
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: 🚨 Error Messages & Logs
      description: |
        Please provide any error messages, stack traces, or relevant logs.

        **How to find logs:**
        1. Open Command Palette (Ctrl+Shift+P)
        2. Run "Developer: Reload Window With Extensions Disabled"
        3. Enable only Keypress Notifications
        4. Check Developer Console (Help > Toggle Developer Tools)
        5. Check Extension Host logs
      placeholder: |
        Example:
        ```
        [2024-01-15 10:30:45] ERROR in Extension Host: 
        Error: Cannot find module '@vscode/vsce'
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
        at Function.Module._load (node:internal/modules/cjs/loader:873:27)
        ```
      render: text
    validations:
      required: false

  - type: textarea
    id: environment-details
    attributes:
      label: 🌍 Environment Details
      description: |
        Provide additional environment information:
        - Development environment (WSL, Docker, Remote, etc.)
        - Keyboard layout/locale
        - Display configuration
        - Any virtualization
      placeholder: |
        Example:
        - WSL2 Ubuntu 22.04 on Windows 11
        - US QWERTY keyboard layout
        - Multiple monitors (different DPI scaling)
        - Running in VMware virtual machine
        - Locale: en-US, Timezone: EST
    validations:
      required: false

  - type: textarea
    id: conflicting-extensions
    attributes:
      label: 🔌 Other Extensions & Potential Conflicts
      description: List other extensions that might be related to the compatibility issue.
      placeholder: |
        Example:
        Potentially conflicting:
        - Vim extension (keybinding overrides)
        - Remote Development extension pack
        - Custom keybinding extensions

        Total extensions: 25
        Tested with all extensions disabled: [Yes/No]
    validations:
      required: false

  - type: checkboxes
    id: compatibility-scope
    attributes:
      label: 🎯 Compatibility Issue Scope
      description: What aspects are affected by this compatibility issue?
      options:
        - label: Extension fails to install
        - label: Extension fails to activate
        - label: Core functionality doesn't work
        - label: Some features work, others don't
        - label: Performance is significantly impacted
        - label: UI/notifications don't display correctly
        - label: Keybinding detection fails
        - label: Configuration settings ignored
        - label: Extension crashes VS Code
        - label: Other extensions stop working

  - type: dropdown
    id: workaround-available
    attributes:
      label: 🔄 Workaround Available?
      description: Have you found any workarounds for this compatibility issue?
      options:
        - ✅ Yes, I found a reliable workaround
        - ⚠️ Yes, but it's partial or unreliable
        - ❌ No workaround found
        - 🤷 Haven't tried finding workarounds
    validations:
      required: true

  - type: textarea
    id: workaround-details
    attributes:
      label: 🛠️ Workaround Details
      description: If you found a workaround, please describe it.
      placeholder: |
        Example:
        - Downgrading to Node.js 20.10.0 resolves the issue
        - Using VS Code Stable instead of Insiders works
        - Disabling specific VS Code settings allows activation
        - Manual installation from VSIX file works

  - type: checkboxes
    id: testing-done
    attributes:
      label: 🧪 Testing & Isolation
      description: What testing have you done to isolate the compatibility issue?
      options:
        - label: Tested with clean VS Code installation
        - label: Tested with all other extensions disabled
        - label: Tested on different OS/architecture
        - label: Tested with different Node.js versions
        - label: Tested with different VS Code versions
        - label: Tested in safe mode / guest user account
        - label: Compared with working environment
        - label: Tested with default VS Code settings

  - type: textarea
    id: working-configuration
    attributes:
      label: ✅ Known Working Configuration
      description: |
        If you know of a configuration where the extension works correctly, please share it.
      placeholder: |
        Example:
        Works correctly on:
        - VS Code 1.94.2 Stable
        - Node.js 20.9.0
        - Windows 11 22H2
        - Extension version 0.0.9

  - type: dropdown
    id: impact-severity
    attributes:
      label: 🚨 Impact Severity
      description: How severely does this compatibility issue affect usage?
      options:
        - 🔴 Critical - Cannot use extension at all
        - 🟠 High - Major features unavailable
        - 🟡 Medium - Some features affected
        - 🟢 Low - Minor compatibility quirks
    validations:
      required: true

  - type: checkboxes
    id: platform-testing
    attributes:
      label: 🌍 Cross-Platform Testing
      description: Would you be able to help test fixes on your platform?
      options:
        - label: I can test on Windows
        - label: I can test on macOS
        - label: I can test on Linux
        - label: I can test different VS Code versions
        - label: I can test different Node.js versions
        - label: I can test in different environments (WSL, Docker, etc.)
        - label: I can help with automated testing

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: |
        Any other information that might help resolve this compatibility issue:
        - When the issue started appearing
        - Recent system/software changes
        - Similar issues in other extensions
        - Business/workflow impact
      placeholder: |
        Example:
        - Issue started after VS Code automatic update to Insiders
        - Our team uses this setup for development standardization
        - Similar Node.js compatibility issues seen in other extensions
        - Blocking deployment to new development machines

  - type: checkboxes
    id: verification
    attributes:
      label: ✅ Verification
      description: Please confirm the following
      options:
        - label: I have checked the official compatibility requirements
          required: true
        - label: I have provided detailed environment information
          required: true
        - label: I have tested with minimal configuration to isolate the issue
          required: true
        - label: I understand that some configurations may not be officially supported
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## 🚀 What happens next?

        1. **🔍 Verification**: We'll verify the compatibility issue in a similar environment
        2. **📊 Analysis**: Analyze the root cause and scope of the compatibility problem
        3. **🎯 Planning**: Determine if this should be supported and plan fixes
        4. **🔧 Implementation**: Make necessary changes for compatibility
        5. **🧪 Testing**: Test across affected configurations
        6. **📦 Release**: Include compatibility fixes in future releases

        **Thank you for helping us improve compatibility!** 🌍

        💡 **Compatibility Tips:**
        - 📋 Keep VS Code and Node.js within supported version ranges
        - 🔄 Test major updates in isolated environments first
        - 📊 Use our compatibility matrix as a reference
        - 🤝 Join our community discussions about platform support

        ---

        🔗 **Compatibility Resources:**
        - [Official Compatibility Matrix](https://vijay431.github.io/vscode-keypress_snackbar_notification-extension/#compatibility)
        - [Supported VS Code Versions](https://github.com/Vijay431/vscode-keypress_snackbar_notification-extension#requirements)
        - [Node.js Compatibility Testing](https://github.com/Vijay431/vscode-keypress_snackbar_notification-extension/actions/workflows/node-compatibility.yml)
        - [Platform-Specific Issues](https://github.com/Vijay431/vscode-keypress_snackbar_notification-extension/labels/compatibility)
