blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion Forum
    url: https://github.com/Vijay431/vscode-keypress_snackbar_notification-extension/discussions
    about: Ask questions and discuss with the community
  - name: 📚 Documentation
    url: https://github.com/Vijay431/vscode-keypress_snackbar_notification-extension#readme
    about: Read the documentation for usage and setup