name: 📚 Documentation Improvement
description: Help us improve our documentation! 📖
title: "[Docs]: "
labels: ["documentation", "good-first-issue", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # 📚 Documentation Improvement

        Thanks for helping improve our documentation! Clear docs make **Keypress Notifications** accessible to everyone. 🎯

        **Before submitting:** Please check our [existing documentation](https://vijay431.github.io/vscode-keypress_snackbar_notification-extension/) to see what's already covered.

  - type: dropdown
    id: doc-type
    attributes:
      label: 📋 Documentation Type
      description: What type of documentation improvement is this?
      options:
        - 🐛 Fix incorrect information
        - ➕ Add missing information
        - 🔄 Update outdated content
        - 🎨 Improve formatting/structure
        - 🌍 Translation/Localization
        - 📱 Accessibility improvements
        - 💡 Add examples/tutorials
        - 🔗 Fix broken links
        - 📖 Reorganize content
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: doc-location
    attributes:
      label: 📍 Documentation Location
      description: Where is the documentation that needs improvement?
      options:
        - README.md (main repository)
        - GitHub Pages site
        - CHANGELOG.md
        - Package.json description
        - Code comments/JSDoc
        - Configuration schema
        - Issue/PR templates
        - GitHub wiki
        - Other file (please specify)
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: 📄 Current Content (if applicable)
      description: |
        If you're reporting incorrect or outdated content, please paste the current text here.
        You can also provide a link to the specific section.
      placeholder: |
        Example:
        Current text: "Supports VS Code 1.80.0+"
        Location: README.md, Requirements section, line 25
        Link: https://github.com/Vijay431/vscode-keypress_snackbar_notification-extension#requirements
      render: markdown

  - type: textarea
    id: issue-description
    attributes:
      label: 🔍 Issue Description
      description: Clearly describe what's wrong or missing in the documentation.
      placeholder: |
        Example:
        - The minimum VS Code version listed is outdated
        - Missing explanation of how to configure custom keybindings
        - Code example doesn't work with latest version
        - Screenshots are outdated and don't match current UI
    validations:
      required: true

  - type: textarea
    id: proposed-content
    attributes:
      label: ✍️ Proposed Content/Changes
      description: |
        What should the documentation say instead? 
        Provide the corrected/improved content if you have it.
      placeholder: |
        Example:
        Suggested text: "Supports VS Code 1.90.0+"

        Or provide a more detailed explanation:
        "To configure custom notifications for specific commands:
        1. Open VS Code settings (Ctrl+,)
        2. Search for 'keypress-notifications'
        3. Add your command to the excludedCommands array..."
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: improvement-areas
    attributes:
      label: 🎯 Areas for Improvement
      description: What aspects of the documentation could be better? (Check all that apply)
      options:
        - label: Clarity - make it easier to understand
        - label: Completeness - add missing information
        - label: Organization - better structure/navigation
        - label: Examples - more practical examples
        - label: Screenshots - add or update images
        - label: Getting Started - improve onboarding
        - label: Troubleshooting - better error resolution
        - label: Advanced Usage - power user features
        - label: API Documentation - technical reference
        - label: Accessibility - screen reader friendly

  - type: dropdown
    id: target-audience
    attributes:
      label: 👥 Target Audience
      description: Who would benefit most from this documentation improvement?
      options:
        - 🆕 New users/beginners
        - 👨‍💻 Regular developers
        - 🚀 Power users/advanced
        - 🏢 Enterprise users
        - 🔧 Contributors/developers
        - 🎓 Students/learners
        - ♿ Users with accessibility needs
        - 🌍 Non-English speakers
        - All users
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🤔 Context & User Experience
      description: |
        Help us understand the context better:
        - What were you trying to do when you encountered this issue?
        - What documentation were you looking for?
        - How did the current docs fall short?
      placeholder: |
        Example:
        "I was trying to set up the extension for the first time and couldn't find clear instructions on how to verify it was working correctly. The README mentions testing with Ctrl+C, but doesn't explain what notification I should expect to see."

  - type: textarea
    id: impact
    attributes:
      label: 📊 Impact Assessment
      description: How does this documentation issue affect users?
      placeholder: |
        Example:
        - Causes confusion during initial setup
        - Prevents users from using advanced features
        - Makes troubleshooting difficult
        - Affects accessibility for screen reader users
    validations:
      required: false

  - type: checkboxes
    id: difficulty
    attributes:
      label: 🎚️ Difficulty Level
      description: How would you rate the difficulty of this improvement?
      options:
        - label: 🟢 Easy - Simple text changes
        - label: 🟡 Medium - Requires some research/testing
        - label: 🟠 Hard - Complex restructuring needed
        - label: 🔴 Expert - Requires deep technical knowledge

  - type: textarea
    id: references
    attributes:
      label: 📚 References & Examples
      description: |
        Share any helpful references:
        - Links to good documentation examples
        - Related GitHub issues
        - External resources
        - Similar extensions' docs
      placeholder: |
        Example:
        - Great example of configuration docs: [VS Code Theme extension]
        - Similar issue in another project: [link]
        - Helpful tutorial format: [link]

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Visual Examples
      description: |
        If applicable, provide screenshots showing:
        - Current confusing documentation
        - Expected UI/behavior
        - Examples from other projects
        - Mockups of improved layout

        You can drag & drop images here!

  - type: checkboxes
    id: contribution-type
    attributes:
      label: 🤝 How You Can Help
      description: Are you willing to contribute to fixing this documentation issue?
      options:
        - label: I can write the improved content
        - label: I can provide screenshots/examples
        - label: I can test the documentation changes
        - label: I can review changes made by others
        - label: I'm just reporting the issue

  - type: dropdown
    id: urgency
    attributes:
      label: ⏰ Urgency Level
      description: How urgent is this documentation fix?
      options:
        - 🔴 Critical - Blocking users from basic functionality
        - 🟠 High - Causing significant confusion
        - 🟡 Medium - Noticeable improvement needed
        - 🟢 Low - Nice to have enhancement
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: 📝 Additional Notes
      description: |
        Any other information that might be helpful:
        - Related documentation that works well
        - Specific user feedback you've received
        - Timeline constraints
        - Accessibility considerations
      placeholder: |
        Example:
        - This came up in multiple user support requests
        - Would be great to have this ready for the next release
        - Consider mobile users when designing layout

  - type: checkboxes
    id: verification
    attributes:
      label: ✅ Verification
      description: Please confirm the following
      options:
        - label: I have checked existing documentation to avoid duplication
          required: true
        - label: I have provided specific, actionable feedback
          required: true
        - label: I understand this is for documentation improvements only
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## 🚀 What happens next?

        1. **🏷️ Triage**: We'll review and categorize your documentation request
        2. **📝 Planning**: Determine scope and priority for the improvement
        3. **✍️ Writing**: Create or update the documentation
        4. **👥 Review**: Community and team review of changes
        5. **📚 Publishing**: Updated documentation goes live

        **Thank you for helping make our documentation better!** 📖

        💡 **Tips for great documentation contributions:**
        - 🎯 Be specific about what needs improvement
        - 👥 Think about different user perspectives
        - 📱 Consider all platforms and accessibility needs
        - ✨ Provide examples when possible

        ---

        📖 **Documentation Resources:**
        - [Current Documentation Site](https://vijay431.github.io/vscode-keypress_snackbar_notification-extension/)
        - [Contributing Guidelines](https://github.com/Vijay431/vscode-keypress_snackbar_notification-extension/blob/master/CONTRIBUTING.md)
        - [Style Guide for Documentation](https://github.com/Vijay431/vscode-keypress_snackbar_notification-extension/wiki/Documentation-Style-Guide)
