# Site settings
title: "Keypress Notifications Documentation"
description: "Complete documentation for the Keypress Notifications VS Code extension"
url: "https://vijay431.github.io"
baseurl: "/keypress-notifications"

# Repository settings
repository: "Vijay431/keypress-notifications"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false

# Theme
remote_theme: just-the-docs/just-the-docs
color_scheme: auto

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Just the Docs theme configuration
# Enable or disable the site search
search_enabled: true

# Set the search token separator
search_tokenizer_separator: /[\s\-/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub": "https://github.com/Vijay431/keypress-notifications"
  "VS Code Marketplace": "https://marketplace.visualstudio.com/items?itemName=VijayGangatharan.keypress-notifications"

# Makes aux links open in a new tab
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2025 Vijay Gangatharan. Made with ❤️ for the VS Code community."

# Color scheme supports "light" (default) and "dark"

# Google Analytics Tracking (uncomment to enable)
# ga_tracking: UA-XXXXXXXX-X
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/false/nil)

# Exclude from processing
exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile

# Collections configuration
collections:
  guides:
    output: true
    permalink: /:collection/:name/
  api:
    output: true
    permalink: /:collection/:name/
  examples:
    output: true
    permalink: /:collection/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "default"
      parent: "Guides"
  - scope:
      path: ""
      type: "api"
    values:
      layout: "default"
      parent: "API Reference"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "default"
      parent: "Examples"

# Navigation structure
nav_sort: case_insensitive

# Enable copy to clipboard button on code blocks
enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edit timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Vijay431/keypress-notifications"
gh_edit_branch: "master"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Site logo
logo: "/assets/images/logo.png"

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Mermaid diagrams
mermaid:
  version: "9.1.6"

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
