name: CI/CD

on:
  push:
    branches: ['**']

permissions:
  contents: read

jobs:
  # Build job - runs on all branches for continuous validation
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install xvfb for headless VS Code testing
      - name: Install System Dependencies
        run: sudo apt-get install -y xvfb

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Extension
        run: npm run build

      - name: Run Extension Tests
        run: xvfb-run --auto-servernum npm test

  # Lint job - runs on all branches for code quality checks
  lint:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Code Formatting
        run: npm run format -- --check

  # Security audit job - runs on all branches for security validation
  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Security Audit
        run: npm audit --audit-level=high

      - name: Check for Known Vulnerabilities
        run: npm audit --audit-level=moderate

  # Dry-run publish job - validates publishing on non-master branches
  dry-run-publish:
    name: Validate Publishing (Dry Run)
    needs: [build, lint, security]
    if: github.ref != 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Validate Extension Package
        run: npm run package

  # Deploy job - ONLY runs on master branch after all checks pass
  deploy:
    name: Deploy to VS Code Marketplace
    needs: [build, lint, security]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://marketplace.visualstudio.com/items?itemName=VijayGangatharan.keypress-notifications

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Package Extension
        run: npm run package

      - name: Publish to VS Code Marketplace
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}

      - name: Create Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: 'keypress-notifications-*.vsix'
          retention-days: 90
